name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  ci:
    uses: vanillaes/.github/.github/workflows/verify.yml@main

  cd-npm:
    needs: ci
    uses: vanillaes/.github/.github/workflows/npm.yml@main
    secrets: inherit

  cd-gh:
    needs: ci
    uses: vanillaes/.github/.github/workflows/gh.yml@main
    secrets: inherit
